### ISSUE TITLE
Do I need to purchase the Anti-Captcha API to bypass CAPTCHAs?

### ISSUE THREAD

**Issue by huazz233** [Zierax/GoogleDorker#2]
Do I need to purchase the Anti-Captcha API to bypass CAPTCHAs? Does it support reCAPTCHA v3? Have you tested the score, and can it achieve a score of 0.7 or higher?

**Comment by Zierax** [comment]
You don't have to buy the Anti-Captcha API to bypass CAPTCHAs, but it's a great tool for automating the process. If you're using the anticaptchaofficial Python library, you'll need an API key, which you get by buying credits on their website.

Anti-Captcha can handle reCAPTCHA v3, but it works differently than v2. Instead of solving a puzzle, reCAPTCHA v3 scores your website interactions. The API tries to mimic human behavior to get a good score (usually around 0.7 or higher). However, the score can vary depending on the website's security measures.

Anti-Captcha generally works well for websites with low to medium security. But it might not always be successful, especially on heavily protected sites. To see how well it works for your specific needs, you should test it on a real website that you control

however you can use `--pre-automated-browsing` for bypass recaptcha manually every 100 to 500 requests attempts.

**Comment by huazz233** [comment]
I still have some doubts, what kind of reCAPTCHA does GoogleDorker support?

**Comment by Zierax** [comment]
all build on user interactions 
example: you will find recaptcha in `-pre-automated-browsing` then you will bypass it manually
